spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loegn/config
#          label: master
          search-paths:
  application:
    name: config-center
  profiles:
    active: peer1
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

---
spring:
  profiles: peer1
server:
  port: 8401

---
spring:
  profiles: peer2
server:
  port: 8402
