spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/loegn/config
#          匹配任意文件夹下的配置
          search-paths: '{application}'
#          label: master
#          search-paths: consumer-config,producer-config
    bus:
      trace:
        enabled: true
  application:
    name: config-center
  profiles:
    active: peer1
# bus
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include:
          - bus-refresh
          - bus-env
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/

---
spring:
  profiles: peer1
server:
  port: 8401

---
spring:
  profiles: peer2
server:
  port: 8402
