spring:
  profiles:
    active: peer1
  application:
    name: consumer
# bus
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      trace:
        enabled: true
#feign
feign:
  hystrix:
    enabled: true
producer:
  name: producer

---
spring:
  profiles: peer1
  # bus
  cloud:
    bus:
      id: 'bus:id'
server:
  port: 8301

---
spring:
  profiles: peer2
server:
  port: 8302
