spring:
  application:
    name: zuul
server:
  port: 8701
#eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8101/eureka/
#是否开启重试功能
zuul:
  retryable: true
  host:
    #超时
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
    max-total-connections: 200
ribbon:
  #对当前服务的重试次数
  MaxAutoRetries: 2
  #切换相同Server的次数
  MaxAutoRetriesNextServer: 0
  #超时
  ReadTimeout: 1000

#zuul:
#  routes:
#    producer:
#      path: '/producer/**'
#      serviceId: producer